# Generated by Django 3.1.7 on 2021-02-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sportdays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, choices=[('0', 'Ma'), ('1', 'Ti'), ('2', 'Ke'), ('3', 'To'), ('4', 'Pe'), ('5', 'La'), ('6', 'Su')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ourauser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=32)),
                ('lastname', models.CharField(blank=True, max_length=32)),
                ('username', models.CharField(blank=True, max_length=24)),
                ('ourakey', models.CharField(blank=True, max_length=64)),
                ('sportdays', models.ManyToManyField(blank=True, to='myOura.Sportdays')),
            ],
        ),
    ]
